// Helpers for rendering images generated by the ComfyUI image/video tools.
//
// The agent's image tool renders a file into ComfyUI's output dir and ships it
// to Telegram; the only trace that reaches the chat API is the rendered file
// *path* embedded in a tool-result string. ComfyUI already serves those files
// over HTTP at GET /view?filename=<name>&type=output, so we extract the
// filename from the tool content and build a fetchable URL the app renders.
import 'dart:io';

import '../models/comfy_workflow.dart';
import 'package:shared_preferences/shared_preferences.dart';

class ComfyUiPrefs {
  static const baseUrl = 'comfyui_base_url';
  static const defaultBaseUrl = 'http://0.0.0.0:8188';

  /// Loads only a user-configured ComfyUI endpoint.
  ///
  /// The historic wildcard default is not reachable from a phone, so it is
  /// migrated to an absent configuration rather than used as an endpoint.
  static Future<ComfyEndpoint?> loadConfiguredEndpoint(
    SharedPreferences prefs,
  ) async {
    final raw = prefs.getString(baseUrl);
    if (raw == null || raw == defaultBaseUrl || raw == '$defaultBaseUrl/') {
      return null;
    }
    return ComfyEndpoint.parse(raw);
  }
}

class ComfyUi {
  ComfyUi._();

  /// A filename with an image or video extension, preceded by a path separator
  /// (so we don't pick up `"src":"foo.png"`-style JSON noise).
  static final RegExp _mediaPathRe = RegExp(
    r'[\\/:]\s*([A-Za-z0-9_\-]+\.(?:png|jpe?g|webp|mp4|webm|mkv|mov|gif))',
    caseSensitive: false,
  );

  static final RegExp _videoExtRe = RegExp(
    r'\.(?:mp4|webm|mkv|mov)$',
    caseSensitive: false,
  );

  /// Trims, adds http:// if missing, strips trailing slash.
  static String normalizeBaseUrl(String raw) {
    var url = raw.trim();
    if (url.isEmpty) return ComfyUiPrefs.defaultBaseUrl;
    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      url = 'http://$url';
    }
    if (url.endsWith('/')) url = url.substring(0, url.length - 1);
    return url;
  }

  /// Loads the configured ComfyUI base URL (or the default).
  static Future<String> loadBaseUrl() async {
    final prefs = await SharedPreferences.getInstance();
    return normalizeBaseUrl(
      prefs.getString(ComfyUiPrefs.baseUrl) ?? ComfyUiPrefs.defaultBaseUrl,
    );
  }

  /// Pulls media filenames out of a tool-result string (which often looks like
  /// `{"output":"...rendered: C:\\...\\output\\TG_00084_.png..."}`).
  static List<String> extractMediaFilenames(String content) {
    final names = <String>{};
    for (final m in _mediaPathRe.allMatches(content)) {
      final name = m.group(1);
      if (name != null && name.isNotEmpty) names.add(name);
    }
    return names.toList();
  }

  /// True if the filename has a video extension.
  static bool isVideo(String filename) => _videoExtRe.hasMatch(filename);

  /// Builds the ComfyUI /view URL for a given filename. [type] is ComfyUI's
  /// own file-source classifier (`output` for generated results, `input` for
  /// uploaded/source images, `temp` for intermediate previews).
  static String viewUrl(
    String baseUrl,
    String filename, {
    String type = 'output',
  }) {
    return ComfyEndpoint.parse(
      normalizeBaseUrl(baseUrl),
    ).viewUri(ComfyOutputRef(filename: filename, type: type)).toString();
  }

  /// True when [baseUri] is plain HTTP to a host whose network scope the app
  /// cannot prove is private, so the settings screen must require explicit
  /// acknowledgement before saving it as the ComfyUI endpoint. HTTPS is
  /// always exempt. A literal loopback, RFC1918, RFC4193, link-local, or
  /// Tailscale/CGNAT (100.64.0.0/10) address is exempt; every other
  /// plain-HTTP host requires acknowledgement -- including a Tailscale
  /// *hostname* (e.g. `foo.tailnet.ts.net`), since a string can't be proven
  /// private the way a literal address in a reserved range can.
  static bool requiresPlainHttpWarning(Uri baseUri) {
    if (baseUri.scheme != 'http') return false;
    final host = baseUri.host;
    final address = InternetAddress.tryParse(host);
    if (address == null) return host.toLowerCase() != 'localhost';
    if (address.isLoopback) return false;
    return switch (address.type) {
      InternetAddressType.IPv4 => !_isExemptIPv4(address.rawAddress),
      InternetAddressType.IPv6 => !_isExemptIPv6(address.rawAddress),
      _ => true,
    };
  }

  static bool _isExemptIPv4(List<int> octets) {
    final a = octets[0];
    final b = octets[1];
    if (a == 10) return true; // RFC1918 10.0.0.0/8
    if (a == 172 && b >= 16 && b <= 31) return true; // RFC1918 172.16.0.0/12
    if (a == 192 && b == 168) return true; // RFC1918 192.168.0.0/16
    if (a == 169 && b == 254) return true; // link-local 169.254.0.0/16
    if (a == 100 && b >= 64 && b <= 127) return true; // CGNAT/Tailscale
    return false;
  }

  static bool _isExemptIPv6(List<int> bytes) {
    final first = bytes[0];
    if (first & 0xfe == 0xfc) return true; // RFC4193 fc00::/7
    if (first == 0xfe && (bytes[1] & 0xc0) == 0x80) return true; // fe80::/10
    return false;
  }
}
