// Helpers for rendering images generated by the ComfyUI image/video tools.
//
// The agent's image tool renders a file into ComfyUI's output dir and ships it
// to Telegram; the only trace that reaches the chat API is the rendered file
// *path* embedded in a tool-result string. ComfyUI already serves those files
// over HTTP at GET /view?filename=<name>&type=output, so we extract the
// filename from the tool content and build a fetchable URL the app renders.
import 'package:shared_preferences/shared_preferences.dart';

class ComfyUiPrefs {
  static const baseUrl = 'comfyui_base_url';
  static const defaultBaseUrl = 'http://0.0.0.0:8188';
}

class ComfyUi {
  ComfyUi._();

  /// A filename with an image or video extension, preceded by a path separator
  /// (so we don't pick up `"src":"foo.png"`-style JSON noise).
  static final RegExp _mediaPathRe = RegExp(
    r'[\\/:]\s*([A-Za-z0-9_\-]+\.(?:png|jpe?g|webp|mp4|webm|mkv|mov|gif))',
    caseSensitive: false,
  );

  static final RegExp _videoExtRe = RegExp(
    r'\.(?:mp4|webm|mkv|mov)$',
    caseSensitive: false,
  );

  /// Trims, adds http:// if missing, strips trailing slash.
  static String normalizeBaseUrl(String raw) {
    var url = raw.trim();
    if (url.isEmpty) return ComfyUiPrefs.defaultBaseUrl;
    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      url = 'http://$url';
    }
    if (url.endsWith('/')) url = url.substring(0, url.length - 1);
    return url;
  }

  /// Loads the configured ComfyUI base URL (or the default).
  static Future<String> loadBaseUrl() async {
    final prefs = await SharedPreferences.getInstance();
    return normalizeBaseUrl(
      prefs.getString(ComfyUiPrefs.baseUrl) ?? ComfyUiPrefs.defaultBaseUrl,
    );
  }

  /// Pulls media filenames out of a tool-result string (which often looks like
  /// `{"output":"...rendered: C:\\...\\output\\TG_00084_.png..."}`).
  static List<String> extractMediaFilenames(String content) {
    final names = <String>{};
    for (final m in _mediaPathRe.allMatches(content)) {
      final name = m.group(1);
      if (name != null && name.isNotEmpty) names.add(name);
    }
    return names.toList();
  }

  /// True if the filename has a video extension.
  static bool isVideo(String filename) => _videoExtRe.hasMatch(filename);

  /// Builds the ComfyUI /view URL for a given output filename.
  static String viewUrl(String baseUrl, String filename) {
    return '${normalizeBaseUrl(baseUrl)}/view?filename=${Uri.encodeComponent(filename)}&type=output';
  }
}
