// Grid of every image in a chat: generated by ComfyUI tool calls and
// photos the user attached, newest last (same order as the transcript).
import 'package:flutter/material.dart';

import '../services/comfyui.dart';
import '../services/connection_manager.dart';
import '../widgets/cached_media_thumbnail.dart';

class MediaGalleryScreen extends StatelessWidget {
  final List<Map<String, dynamic>> messages;
  final String comfyBaseUrl;

  const MediaGalleryScreen({
    required this.messages,
    required this.comfyBaseUrl,
    super.key,
  });

  List<String> _collectImageUrls() {
    // A filename can legitimately resurface in tool content more than once
    // (e.g. a post-render verification step that lists the output dir) —
    // dedup by URL so the same picture doesn't get a second gallery tile.
    final seen = <String>{};
    final urls = <String>[];
    for (final msg in messages) {
      final role = (msg['role'] as String?) ?? '';
      if (role == 'tool') {
        final raw = (msg['content'] as String?) ?? '';
        for (final name in ComfyUi.extractMediaFilenames(raw)) {
          if (!ComfyUi.isVideo(name)) {
            final url = ComfyUi.viewUrl(comfyBaseUrl, name);
            if (seen.add(url)) urls.add(url);
          }
        }
      } else if (role == 'user') {
        for (final url in parseMessageContent(msg['content']).imageUrls) {
          if (seen.add(url)) urls.add(url);
        }
      }
    }
    return urls;
  }

  @override
  Widget build(BuildContext context) {
    final urls = _collectImageUrls();
    return Scaffold(
      appBar: AppBar(title: Text('Images (${urls.length})')),
      body: urls.isEmpty
          ? Center(
              child: Text(
                'No images yet',
                style: Theme.of(context).textTheme.titleMedium,
              ),
            )
          : GridView.builder(
              padding: const EdgeInsets.all(4),
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 3,
                crossAxisSpacing: 4,
                mainAxisSpacing: 4,
              ),
              itemCount: urls.length,
              itemBuilder: (context, i) =>
                  CachedMediaThumbnail(url: urls[i], borderRadius: 4),
            ),
    );
  }
}
