// Grid of every image in a chat: generated by ComfyUI tool calls and
// photos the user attached, newest last (same order as the transcript).
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/material.dart';

import '../services/comfyui.dart';
import '../services/connection_manager.dart';

class MediaGalleryScreen extends StatelessWidget {
  final List<Map<String, dynamic>> messages;
  final String comfyBaseUrl;

  const MediaGalleryScreen({
    required this.messages,
    required this.comfyBaseUrl,
    super.key,
  });

  List<String> _collectImageUrls() {
    final urls = <String>[];
    for (final msg in messages) {
      final role = (msg['role'] as String?) ?? '';
      if (role == 'tool') {
        final raw = (msg['content'] as String?) ?? '';
        for (final name in ComfyUi.extractMediaFilenames(raw)) {
          if (!ComfyUi.isVideo(name)) {
            urls.add(ComfyUi.viewUrl(comfyBaseUrl, name));
          }
        }
      } else if (role == 'user') {
        urls.addAll(parseMessageContent(msg['content']).imageUrls);
      }
    }
    return urls;
  }

  @override
  Widget build(BuildContext context) {
    final urls = _collectImageUrls();
    return Scaffold(
      appBar: AppBar(title: Text('Images (${urls.length})')),
      body: urls.isEmpty
          ? Center(
              child: Text(
                'No images yet',
                style: Theme.of(context).textTheme.titleMedium,
              ),
            )
          : GridView.builder(
              padding: const EdgeInsets.all(4),
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 3,
                crossAxisSpacing: 4,
                mainAxisSpacing: 4,
              ),
              itemCount: urls.length,
              itemBuilder: (context, i) => _GalleryTile(url: urls[i]),
            ),
    );
  }
}

class _GalleryTile extends StatelessWidget {
  final String url;
  const _GalleryTile({required this.url});

  Uint8List? get _dataBytes {
    if (!url.startsWith('data:')) return null;
    final comma = url.indexOf(',');
    if (comma < 0) return null;
    try {
      return base64Decode(url.substring(comma + 1));
    } catch (_) {
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    final bytes = _dataBytes;
    final thumb = bytes != null
        ? Image.memory(bytes, fit: BoxFit.cover)
        : Image.network(
            url,
            fit: BoxFit.cover,
            errorBuilder: (_, _, _) => Container(
              color: Theme.of(context).colorScheme.surfaceContainerHighest,
              child: const Icon(Icons.broken_image_outlined),
            ),
          );

    return GestureDetector(
      onTap: () => Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => Scaffold(
            backgroundColor: Colors.black,
            appBar: AppBar(backgroundColor: Colors.black),
            body: SafeArea(
              child: Center(
                child: InteractiveViewer(
                  child: bytes != null ? Image.memory(bytes) : Image.network(url),
                ),
              ),
            ),
          ),
        ),
      ),
      child: ClipRRect(borderRadius: BorderRadius.circular(4), child: thumb),
    );
  }
}
